name: Deploy EKS Cluster - CI

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Get
        working-directory: "./Terraform-AWS-Resources/EKS-Worker-Nodes"
        run: terraform get --update

      - name: Terraform Init
        id: init
        working-directory: "./Terraform-AWS-Resources/EKS-Worker-Nodes"
        run: terraform init

      - name: Terraform Plan
        id: plan
        working-directory: "./Terraform-AWS-Resources/EKS-Worker-Nodes"
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        working-directory: "./Terraform-AWS-Resources/EKS-Worker-Nodes"
        run: terraform apply -auto-approve